language: python
python:
    - "3.7"
env:
    - QT_QPA_PLATFORM=offscreen
before_install:
    - sudo apt-get update
    - pip install poetry
install:
    - poetry install
script:
    - inv lint
    - pytest --cov-report term --cov=usc_lr_timer tests -v
after_success:
    - coveralls
 